services:
    _defaults:
        autowire: true
        autoconfigure: true

    SymfonyBundle\UIBundle\Foundation\:
        resource: '../../../src/*'
        exclude:
            - '../../../src/DependencyInjection/'

    SymfonyBundle\UIBundle\Foundation\Core\Dto\Locale:
        arguments: [ '%locale%' ]